// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viupoccwdvktfktmazfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpdXBvY2N3ZHZrdGZrdG1hemZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NjEzODUsImV4cCI6MjA3NTMzNzM4NX0.00zVxoSHhIL_sQmnJhnM8Ftv39ZyLx_WhHTY3RfizXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});